version: '3'

services:
  gateway:
    build: 
      context: ./
      dockerfile: gateway-dockerfile.dockerfile
    container_name: gateway
    ports:
      - 80:80
      - 8080:8080
    networks:
      - e-commerce

networks:
  e-commerce:
    external: true