version: '3'


services:
  orders:
    build: 
      context: .
      dockerfile: ./orders-dockerfile.dockerfile
    container_name: orders-micro
    ports:
      - 4000:4000
    networks:
      - e-commerce
    depends_on:
      - ordersDB
  
  ordersDB:
    image: mongo:latest
    container_name: orders-micro-db
    networks:
        - e-commerce

networks:
  e-commerce:
    external: true