version: '3'


services:
  products:
    build: 
      context: .
      dockerfile: ./products-dockerfile.dockerfile
    container_name: products-micro
    ports:
      - 8000:8000
    networks:
      - e-commerce
    environment:
      - PORT=8000
      - MONGODB_URI=mongodb://products-micro-db:27017
    depends_on:
      - productsDB
  
  productsDB:
    image: mongo:latest
    container_name: products-micro-db
    networks:
        - e-commerce

networks:
  e-commerce:
    external: true