version: '3'


services:
  products:
    build: 
      context: .
      dockerfile: ./products-dockerfile.dockerfile
    container_name: products-micro
    ports:
      - 8000:8000
    networks:
      - e-commerce
    depends_on:
      - productsDB
  
  productsDB:
    image: mongo:latest
    container_name: products-micro-db
    ports:
      - 27017:27017
    networks:
        - e-commerce

networks:
  e-commerce:
    external: true