// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Order struct {
	ID            string `json:"id"`
	UserID        string `json:"userID"`
	Quantity      int    `json:"quantity"`
	UserFirstName string `json:"userFirstName"`
	UserLastName  string `json:"userLastName"`
	Role          string `json:"role"`
}

type OrderInput struct {
	UserID    string `json:"userID"`
	ProductID string `json:"productID"`
	Quantity  int    `json:"quantity"`
}

type Product struct {
	ID              string `json:"id"`
	Name            string `json:"name"`
	Quantity        int    `json:"quantity"`
	SellerID        string `json:"sellerID"`
	SellerFirstName string `json:"sellerFirstName"`
	SellerLastName  string `json:"sellerLastName"`
}

type ProductInput struct {
	Name     string `json:"name"`
	Quantity int    `json:"quantity"`
	SellerID string `json:"sellerID"`
}

type Query struct {
}

type RegisterInput struct {
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
	Email     string `json:"email"`
	Password  string `json:"password"`
	Role      string `json:"role"`
}

type User struct {
	ID        string `json:"id"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
	Email     string `json:"email"`
	Role      string `json:"role"`
}
